# fly.toml app configuration file generated for mq-test on 2023-09-05T20:09:58+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mq-test"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
